sqlContext.sql("CREATE DATABASE cw2database").show()
sqlContext.sql("use cw2database").show()
sqlContext.sql("CREATE TABLE places (gPlusPlaceId VARCHAR(100),name VARCHAR(100),price VARCHAR(50),address VARCHAR(100),hours VARCHAR(50),phone VARCHAR(50),closed VARCHAR(100))row format delimited fields terminated by '\t'")
sqlContext.sql("LOAD DATA INPATH '/user/cloudera/CW2/Datasets/places.csv' OVERWRITE INTO TABLE places")
sqlContext.sql("CREATE TABLE reviews (gPlusPlaceId VARCHAR(100),gPlaceUserId VARCHAR(100),rating FLOAT,reviewerName VARCHAR(100),reviewText string,categories VARCHAR(100),reviewTime VARCHAR(50))row format delimited fields terminated by '\t'")
val df = sqlContext.sql("SELECT COUNT(reviews.gplusplaceid) AS TotReviews, places.gplusplaceid,places.name FROM places INNER JOIN reviews ON places.gplusplaceid = reviews.gplusplaceid Group By places.gplusplaceid, places.name ORDER BY TotReviews DESC LIMIT 1").show()
System.exit(0)
